import { TENDER_SOURCES, type TenderSourceId } from "./constants.ts";
import type { TenderSourceCatalogEntry } from "./types.ts";

export const TENDER_SOURCE_CATALOG = [
  {
    id: "sam_gov",
    label: "SAM.gov",
    checkboxLabel: "SAM.gov (US Federal)",
    category: "government",
    url: "https://sam.gov/content/opportunities",
    description: "US federal contract opportunities.",
  },
  {
    id: "ted_eu",
    label: "TED EU",
    checkboxLabel: "TED EU",
    category: "government",
    url: "https://ted.europa.eu/en/",
    description: "European public procurement notices.",
  },
  {
    id: "ungm",
    label: "UNGM",
    checkboxLabel: "UNGM",
    category: "un_agency",
    url: "https://www.ungm.org/Public/Notice",
    description: "United Nations agency procurement notices.",
  },
  {
    id: "world_bank",
    label: "World Bank Procurement",
    checkboxLabel: "World Bank",
    category: "multilateral",
    url: "https://projects.worldbank.org/en/projects-operations/procurement",
    description: "World Bank procurement notices and project opportunities.",
  },
  {
    id: "ppra_pk",
    label: "Federal PPRA / EPMS",
    checkboxLabel: "Federal PPRA",
    category: "domestic",
    url: "https://epms.ppra.gov.pk/public/tenders/active-tenders",
    description: "Pakistan federal public procurement tenders from EPMS.",
  },
  {
    id: "eprocure_pk",
    label: "Pakistan e-Procurement",
    checkboxLabel: "eProcure Pakistan",
    category: "domestic",
    url: "https://eprocure.gov.pk/",
    description: "Pakistan e-procurement portal; public tender data is covered by EPMS where available.",
  },
  {
    id: "ppra_punjab",
    label: "Punjab PPRA",
    checkboxLabel: "Punjab PPRA",
    category: "domestic",
    url: "https://ppra.punjab.gov.pk/",
    description: "Punjab procurement authority portal.",
  },
  {
    id: "kppra",
    label: "Khyber Pakhtunkhwa PPRA",
    checkboxLabel: "KP PPRA",
    category: "domestic",
    url: "https://kppra.gov.pk/",
    description: "Khyber Pakhtunkhwa procurement authority portal.",
  },
  {
    id: "ppra_sindh",
    label: "Sindh PPRA",
    checkboxLabel: "Sindh PPRA",
    category: "domestic",
    url: "https://www.pprasindh.gov.pk/",
    description: "Sindh public procurement authority portal.",
  },
  {
    id: "bppra_balochistan",
    label: "Balochistan PPRA",
    checkboxLabel: "Balochistan PPRA",
    category: "domestic",
    url: "https://bppra.gob.pk/",
    description: "Balochistan public procurement authority portal.",
  },
  {
    id: "pda_pk",
    label: "Pakistan Digital Authority",
    checkboxLabel: "PDA",
    category: "it_digital",
    url: "https://www.pda.gov.pk/procurement.php",
    description: "Pakistan Digital Authority procurement notices.",
  },
  {
    id: "nitb_pk",
    label: "National Information Technology Board",
    checkboxLabel: "NITB",
    category: "it_digital",
    url: "https://nitb.gov.pk/tender.html",
    description: "National Information Technology Board procurement and tender notices.",
  },
  {
    id: "pseb_pk",
    label: "Pakistan Software Export Board",
    checkboxLabel: "PSEB",
    category: "it_digital",
    url: "https://pseb.org.pk/",
    description: "Pakistan Software Export Board procurement and tender notices.",
  },
  {
    id: "nadra_pk",
    label: "NADRA",
    checkboxLabel: "NADRA",
    category: "it_digital",
    url: "https://www.nadra.gov.pk/careers-tenders/",
    description: "NADRA procurement and tender notices.",
  },
  {
    id: "planning_commission_pk",
    label: "Planning Commission",
    checkboxLabel: "Planning Commission",
    category: "planning_data",
    url: "https://pc.gov.pk/web/tender",
    description: "Planning Commission procurement and tender notices.",
  },
  {
    id: "urban_unit_pk",
    label: "The Urban Unit",
    checkboxLabel: "Urban Unit",
    category: "planning_data",
    url: "https://urbanunit.gov.pk/procurement",
    description: "The Urban Unit procurement notices.",
  },
  {
    id: "sop_pk",
    label: "Survey of Pakistan",
    checkboxLabel: "Survey of Pakistan",
    category: "planning_data",
    url: "https://www.sop.gov.pk/Tenders",
    description: "Survey of Pakistan tender notices.",
  },
  {
    id: "ppwd_pk",
    label: "Pakistan Public Works Department",
    checkboxLabel: "Pak PWD",
    category: "planning_data",
    url: "https://www.ppwd.gov.pk/",
    description: "Pakistan Public Works Department procurement and tender notices.",
  },
  {
    id: "pitb_pk",
    label: "Punjab Information Technology Board",
    checkboxLabel: "PITB",
    category: "it_digital",
    url: "https://pitb.gov.pk/tendernotices",
    description: "PITB tender notices.",
  },
  {
    id: "ignite_pk",
    label: "Ignite National Technology Fund",
    checkboxLabel: "Ignite",
    category: "it_digital",
    url: "https://ignite.org.pk/rfps/",
    description: "Ignite RFPs, EOIs, tender notices, and evaluation reports.",
  },
  {
    id: "adb",
    label: "Asian Development Bank",
    checkboxLabel: "ADB",
    category: "international",
    url: "https://www.adb.org/work-with-us/procurement",
    description: "ADB procurement notices and project opportunities.",
  },
  {
    id: "undp",
    label: "UNDP Procurement Notices",
    checkboxLabel: "UNDP",
    category: "un_agency",
    url: "https://procurement-notices.undp.org/",
    description: "UNDP procurement notice RSS feeds.",
  },
  {
    id: "etimad_sa",
    label: "Etimad Saudi Arabia",
    checkboxLabel: "Etimad KSA",
    category: "gcc",
    url: "https://etimad.sa/",
    description: "Saudi Arabia national e-procurement platform.",
  },
  {
    id: "kuwait_capt",
    label: "Kuwait CAPT",
    checkboxLabel: "Kuwait CAPT",
    category: "gcc",
    url: "https://capt.gov.kw/en/",
    description: "Kuwait Central Agency for Public Tenders.",
  },
  {
    id: "kuwait_egov_ctc",
    label: "Kuwait Government Online CTC",
    checkboxLabel: "Kuwait eGov CTC",
    category: "gcc",
    url: "https://e.gov.kw/sites/kgoenglish/Pages/eServices/CTC/OnlineTenderMain.aspx",
    description: "Kuwait Government Online tender opening service.",
  },
  {
    id: "kuwait_cbk",
    label: "Central Bank of Kuwait Tendering",
    checkboxLabel: "CBK Tendering",
    category: "gcc",
    url: "https://tendering.cbk.gov.kw",
    description: "Central Bank of Kuwait tendering portal.",
  },
  {
    id: "uk_find_a_tender",
    label: "UK Find a Tender",
    checkboxLabel: "UK Find a Tender",
    category: "government",
    url: "https://www.find-tender.service.gov.uk/",
    description: "Above-threshold UK public procurement notices.",
  },
  {
    id: "uk_contracts_finder",
    label: "UK Contracts Finder",
    checkboxLabel: "UK Contracts Finder",
    category: "government",
    url: "https://www.contractsfinder.service.gov.uk/",
    description: "UK public sector contract opportunities.",
  },
] as const satisfies readonly TenderSourceCatalogEntry[];

export const TENDER_SOURCE_CATALOG_BY_ID = Object.fromEntries(
  TENDER_SOURCE_CATALOG.map((source) => [source.id, source]),
) as Record<TenderSourceId, TenderSourceCatalogEntry>;

export function getTenderSourceCatalogEntry(source: TenderSourceId): TenderSourceCatalogEntry {
  return TENDER_SOURCE_CATALOG_BY_ID[source];
}

const catalogIds = TENDER_SOURCE_CATALOG.map((source) => source.id);
const missingCatalogIds = TENDER_SOURCES.filter((source) => !catalogIds.includes(source));

if (missingCatalogIds.length > 0) {
  throw new Error(`Missing tender source catalog metadata for: ${missingCatalogIds.join(", ")}`);
}
